from __future__ import annotations
from typing import Protocol, runtime_checkable


@runtime_checkable
class StorageEngine(Protocol):
    def create_collection(self, name: str) -> None: ...
    def get_or_create_collection(self, name: str) -> None: ...
    def list_collections(self) -> list[str]: ...
    def delete_collection(self, name: str) -> None: ...
    def save_document(self, collection: str, doc_id: str, doc: dict) -> None: ...
    def find_document_by_hash(self, collection: str, file_hash: str) -> str | None: ...
    def get_document(self, collection: str, doc_id: str) -> dict: ...
    def get_document_structure(self, collection: str, doc_id: str) -> list: ...
    def get_pages(self, collection: str, doc_id: str) -> list | None: ...
    def list_documents(self, collection: str) -> list[dict]: ...
    def delete_document(self, collection: str, doc_id: str) -> None: ...
    def close(self) -> None: ...
